require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  Severity: error

Bundler/DuplicatedGem:
  Enabled: true

Bundler/OrderedGems:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Lint/ScriptPermission:
  Exclude:
    - "Rakefile"

Metrics/AbcSize:
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Max: 25
  Exclude:
    - "spec/**/*_spec.rb"

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/Documentation:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    [
      "to",
      "to_not",
      "require",
      "require_relative",
      "describe",
      "it",
      "context",
      "exit",
      "validate_presence_of",
      "belong_to",
      "have_many",
      "raise",
      "puts",
      "desc",
      "redirect_to",
      "render",
    ]
  Enabled: true
  Exclude:
    - "Gemfile"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

RSpec/DescribeClass:
  Enabled: true

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false # This is incompatible with the way we are testing commands with user input

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/LeadingSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/InstanceVariable:
  AssignmentOnly: false

RSpec/FactoryBot:
  Enabled: false
